-- ============================================================================
-- QUICK FIX FOR SETTINGS RLS ISSUE
-- ============================================================================
-- Simple script to disable RLS and create default settings record
-- ============================================================================

BEGIN;

-- Disable RLS on settings table
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;

-- Create/update default settings record
INSERT INTO public.settings (
    id,
    company_name,
    company_description,
    company_email,
    company_phone,
    company_address,
    business_name,
    registration_number,
    tax_id,
    tagline,
    company_logo,
    logo_url,
    primary_color,
    secondary_color,
    timezone,
    currency,
    is_vat_registered,
    tax_rate,
    prices_include_tax,
    show_prices_with_tax,
    enable_tax_exempt,
    invoice_footer_text,
    free_shipping_threshold,
    standard_shipping_cost,
    express_shipping_cost,
    enable_local_delivery,
    notification_settings,
    maintenance_mode,
    debug_mode,
    enable_reviews,
    enable_wishlist,
    enable_notifications,
    session_timeout,
    max_login_attempts,
    backup_frequency,
    cache_duration
) VALUES (
    '1',
    'Jean Darcel',
    'Professional e-commerce solution for modern businesses',
    'admin1@gisele.co.il',
    '+972-XX-XXX-XXXX',
    'Company Address',
    'Jean Darcel Business',
    '123456789',
    '987654321',
    'Professional e-commerce solution',
    '',
    '',
    '#1976d2',
    '#dc004e',
    'Asia/Jerusalem',
    'ILS',
    true,
    0.18,
    true,
    true,
    false,
    'Thank you for your business!',
    0.00,
    0.00,
    0.00,
    true,
    '{"categories": {"orders": {"sms": false, "push": true, "email": true, "inApp": true}, "system": {"sms": false, "push": true, "email": true, "inApp": true}, "customers": {"sms": false, "push": false, "email": false, "inApp": true}, "inventory": {"sms": false, "push": false, "email": true, "inApp": true}}}',
    false,
    false,
    true,
    true,
    true,
    3600,
    5,
    'daily',
    300
) ON CONFLICT (id) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_description = EXCLUDED.company_description,
    company_email = EXCLUDED.company_email,
    company_phone = EXCLUDED.company_phone,
    company_address = EXCLUDED.company_address,
    business_name = EXCLUDED.business_name,
    registration_number = EXCLUDED.registration_number,
    tax_id = EXCLUDED.tax_id,
    tagline = EXCLUDED.tagline,
    company_logo = EXCLUDED.company_logo,
    logo_url = EXCLUDED.logo_url,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    timezone = EXCLUDED.timezone,
    currency = EXCLUDED.currency,
    is_vat_registered = EXCLUDED.is_vat_registered,
    tax_rate = EXCLUDED.tax_rate,
    prices_include_tax = EXCLUDED.prices_include_tax,
    show_prices_with_tax = EXCLUDED.show_prices_with_tax,
    enable_tax_exempt = EXCLUDED.enable_tax_exempt,
    invoice_footer_text = EXCLUDED.invoice_footer_text,
    free_shipping_threshold = EXCLUDED.free_shipping_threshold,
    standard_shipping_cost = EXCLUDED.standard_shipping_cost,
    express_shipping_cost = EXCLUDED.express_shipping_cost,
    enable_local_delivery = EXCLUDED.enable_local_delivery,
    notification_settings = EXCLUDED.notification_settings,
    maintenance_mode = EXCLUDED.maintenance_mode,
    debug_mode = EXCLUDED.debug_mode,
    enable_reviews = EXCLUDED.enable_reviews,
    enable_wishlist = EXCLUDED.enable_wishlist,
    enable_notifications = EXCLUDED.enable_notifications,
    session_timeout = EXCLUDED.session_timeout,
    max_login_attempts = EXCLUDED.max_login_attempts,
    backup_frequency = EXCLUDED.backup_frequency,
    cache_duration = EXCLUDED.cache_duration,
    updated_at = NOW();

COMMIT;
